import { useRef,useState } from 'react';
import { useQuery,useQueryClient } from '@tanstack/react-query';
import { Plus,Package,ImagePlus,X,Trash2 } from 'lucide-react';
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { getAuthHeaders } from '@/lib/supabase';
import { useToast } from '@/hooks/use-toast';

type Variant={color:string;size:string};
const empty={sku:'',name:'',description:'',price:'',stock:'',unitsPerBox:'1',minOrderQty:'1',seller:'',collectionName:'',tags:'',features:'',imageData:''};
export default function B2BUrunler(){
 const qc=useQueryClient(),{toast}=useToast();const {data=[]}=useQuery<any[]>({queryKey:['/api/commerce/products']});
 const [open,setOpen]=useState(false),[saving,setSaving]=useState(false),[f,setF]=useState(empty),[variants,setVariants]=useState<Variant[]>([{color:'',size:''}]);const fileRef=useRef<HTMLInputElement>(null);
 const field=(k:keyof typeof empty,v:string)=>setF(x=>({...x,[k]:v}));
 const image=(file?:File)=>{if(!file)return;if(file.size>5*1024*1024)return toast({title:'Görsel çok büyük',description:'En fazla 5 MB görsel yükleyin.',variant:'destructive'});const r=new FileReader();r.onload=()=>field('imageData',String(r.result||''));r.readAsDataURL(file);};
 const add=async()=>{setSaving(true);try{const payload={...f,price:Number(f.price),stock:Number(f.stock),unitsPerBox:Number(f.unitsPerBox),minOrderQty:Number(f.minOrderQty),features:f.features.split('\n').map(x=>x.trim()).filter(Boolean),tags:f.tags.split(',').map(x=>x.trim()).filter(Boolean),variants:variants.filter(v=>v.color.trim()||v.size.trim())};const r=await fetch('/api/commerce/products',{method:'POST',headers:{...await getAuthHeaders(),'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Ürün eklenemedi');setF(empty);setVariants([{color:'',size:''}]);setOpen(false);qc.invalidateQueries({queryKey:['/api/commerce/products']});toast({title:'Ürün eklendi',description:'Ürün Çalışkan B2B kataloğuna kaydedildi.'});}catch(e:any){toast({title:'Ürün eklenemedi',description:e.message,variant:'destructive'});}finally{setSaving(false);}};
 return <div className="p-6 space-y-5 overflow-auto h-full bg-muted/20">
  <div className="flex items-center justify-between gap-4"><div><h1 className="text-2xl font-semibold">Ürünler</h1><p className="text-muted-foreground">Çalışkan B2B toptan ürün kataloğunu yönetin.</p></div><Button onClick={()=>setOpen(true)}><Plus className="h-4 w-4 mr-2"/>Ürün Ekle</Button></div>
  <Card><CardHeader><CardTitle className="flex gap-2"><Package className="h-5 w-5"/>B2B Katalog ({data.length})</CardTitle></CardHeader><CardContent>{data.length?<div className="space-y-2">{data.map(p=><div key={p.id} className="grid grid-cols-[52px_1fr] md:grid-cols-[52px_1fr_140px_100px_100px_90px] items-center gap-3 border rounded-lg p-3 text-sm">{p.image_data?<img src={p.image_data} className="h-12 w-12 rounded-md object-cover border"/>:<div className="h-12 w-12 rounded-md bg-muted flex items-center justify-center"><Package className="h-5 w-5"/></div>}<div><b className="block">{p.name}</b><span className="text-xs text-muted-foreground">{p.sku}{p.collection_name?` · ${p.collection_name}`:''}</span></div><span>{Number(p.price).toLocaleString('tr-TR',{style:'currency',currency:'TRY'})}</span><span>Stok: {p.stock}</span><span>Koli: {p.units_per_box||1}</span><span>{p.is_active?'Aktif':'Pasif'}</span></div>)}</div>:<div className="py-14 text-center text-muted-foreground">Henüz B2B ürünü eklenmedi.</div>}</CardContent></Card>
  {open&&<div className="fixed inset-0 z-50 bg-black/45 flex items-center justify-center p-4" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><div className="bg-background border shadow-2xl rounded-2xl w-full max-w-6xl max-h-[92vh] overflow-hidden flex flex-col"><div className="flex items-center justify-between px-6 py-4 border-b"><div><h2 className="text-xl font-semibold">Yeni Ürün Ekle</h2><p className="text-sm text-muted-foreground">Toptan satış ürün bilgilerini ve varyantlarını oluşturun.</p></div><Button size="icon" variant="ghost" onClick={()=>setOpen(false)}><X className="h-5 w-5"/></Button></div><div className="overflow-auto p-6"><div className="grid gap-6 lg:grid-cols-[1.65fr_.85fr]">
   <div className="space-y-6">
    <section className="rounded-xl border p-5 space-y-4"><h3 className="font-semibold">Ürün Bilgileri</h3><div className="grid gap-4 md:grid-cols-2"><div><Label>SKU / Stok Kodu</Label><Input value={f.sku} onChange={e=>field('sku',e.target.value)} placeholder="CLK-001"/></div><div><Label>Ürün Başlığı</Label><Input value={f.name} onChange={e=>field('name',e.target.value)} placeholder="Ürün başlığı"/></div></div><div><Label>Açıklama</Label><textarea className="mt-1 min-h-28 w-full rounded-md border bg-background px-3 py-2 text-sm" value={f.description} onChange={e=>field('description',e.target.value)} placeholder="Ürün açıklaması..."/></div><div><Label>Ürün Görseli</Label><input ref={fileRef} type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={e=>image(e.target.files?.[0])}/><button type="button" onClick={()=>fileRef.current?.click()} className="mt-1 w-full min-h-36 rounded-xl border border-dashed flex items-center justify-center overflow-hidden bg-muted/20">{f.imageData?<img src={f.imageData} className="max-h-52 w-full object-contain"/>:<div className="text-center text-muted-foreground"><ImagePlus className="h-7 w-7 mx-auto mb-2"/><span className="text-sm">Ürün görseli yükle</span></div>}</button></div><div><Label>Ürün Özellikleri</Label><textarea className="mt-1 min-h-28 w-full rounded-md border bg-background px-3 py-2 text-sm" value={f.features} onChange={e=>field('features',e.target.value)} placeholder={'Her özelliği yeni satıra yazın\nGüç: 2000W\nGaranti: 2 Yıl'}/></div></section>
    <section className="rounded-xl border p-5 space-y-4"><div className="flex justify-between"><div><h3 className="font-semibold">Varyantlar</h3><p className="text-sm text-muted-foreground">Renk ve beden seçeneklerini ekleyin.</p></div><Button variant="outline" size="sm" onClick={()=>setVariants(v=>[...v,{color:'',size:''}])}><Plus className="h-4 w-4 mr-1"/>Varyant</Button></div>{variants.map((v,i)=><div key={i} className="grid grid-cols-[1fr_1fr_auto] gap-3"><Input placeholder="Renk" value={v.color} onChange={e=>setVariants(x=>x.map((a,j)=>j===i?{...a,color:e.target.value}:a))}/><Input placeholder="Beden" value={v.size} onChange={e=>setVariants(x=>x.map((a,j)=>j===i?{...a,size:e.target.value}:a))}/><Button size="icon" variant="ghost" disabled={variants.length===1} onClick={()=>setVariants(x=>x.filter((_,j)=>j!==i))}><Trash2 className="h-4 w-4"/></Button></div>)}</section>
    <section className="rounded-xl border p-5"><h3 className="font-semibold mb-4">Stok ve Toptan Satış</h3><div className="grid gap-4 md:grid-cols-4"><div><Label>Satış Fiyatı</Label><Input type="number" value={f.price} onChange={e=>field('price',e.target.value)} placeholder="0,00"/></div><div><Label>Stok</Label><Input type="number" value={f.stock} onChange={e=>field('stock',e.target.value)}/></div><div><Label>Koli İçi Adet</Label><Input type="number" min="1" value={f.unitsPerBox} onChange={e=>field('unitsPerBox',e.target.value)}/></div><div><Label>Minimum Satın Alma Adedi</Label><Input type="number" min="1" value={f.minOrderQty} onChange={e=>field('minOrderQty',e.target.value)}/></div></div></section>
   </div>
   <aside className="space-y-5"><section className="rounded-xl border p-5 space-y-4"><h3 className="font-semibold">Satış Organizasyonu</h3><div><Label>Satıcı</Label><Input value={f.seller} onChange={e=>field('seller',e.target.value)} placeholder="Satıcı / firma"/></div><div><Label>Koleksiyona Ata</Label><Input value={f.collectionName} onChange={e=>field('collectionName',e.target.value)} placeholder="Koleksiyon adı"/></div><div><Label>Etiket Ekle</Label><Input value={f.tags} onChange={e=>field('tags',e.target.value)} placeholder="Yeni, Kampanya, Çok Satan"/><p className="mt-1 text-xs text-muted-foreground">Etiketleri virgülle ayırın.</p></div></section><section className="rounded-xl border p-5"><h3 className="font-semibold mb-3">Yayın Özeti</h3><div className="space-y-2 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Stok</span><b>{f.stock||0}</b></div><div className="flex justify-between"><span className="text-muted-foreground">Koli içi</span><b>{f.unitsPerBox||1}</b></div><div className="flex justify-between"><span className="text-muted-foreground">Minimum alım</span><b>{f.minOrderQty||1}</b></div><div className="flex justify-between"><span className="text-muted-foreground">Varyant</span><b>{variants.filter(v=>v.color||v.size).length}</b></div></div></section></aside>
  </div></div><div className="border-t px-6 py-4 flex justify-end gap-3"><Button variant="outline" onClick={()=>setOpen(false)}>İptal</Button><Button disabled={saving||!f.sku.trim()||!f.name.trim()} onClick={add}>{saving?'Kaydediliyor…':'Ürünü Kaydet'}</Button></div></div></div>}
 </div>;
}
