import { Link } from 'wouter';
import { User,Building2,MapPin,Receipt,CreditCard,Headphones,Lock,KeyRound,Trash2,ChevronRight,Package } from 'lucide-react';
const items=[
 {icon:User,title:'Kullanıcı Bilgileri',desc:'Ad, soyad, telefon ve iletişim bilgilerinizi yönetin.'},
 {icon:Building2,title:'Firma Ayarları',desc:'Firma adı, vergi bilgileri ve işletme profilinizi düzenleyin.'},
 {icon:MapPin,title:'Kayıtlı Adreslerim',desc:'Teslimat ve firma adreslerinizi yönetin.'},
 {icon:Receipt,title:'Fatura Bilgilerim',desc:'Fatura ünvanı, vergi dairesi ve fatura adresi.'},
 {icon:CreditCard,title:'Ödeme Bilgilerim',desc:'Ödeme tercihlerinizi ve kayıtlı yöntemleri görüntüleyin.'},
 {icon:Headphones,title:'Destek Hattı',desc:'Sipariş, ürün ve hesap konularında destek alın.'},
 {icon:Lock,title:'Şifre Değiştir',desc:'Mevcut şifrenizi güvenli şekilde güncelleyin.'},
 {icon:KeyRound,title:'Şifremi Unuttum',desc:'E-posta üzerinden yeni şifre oluşturma bağlantısı alın.'},
];
export default function StoreAccount(){return <div className="min-h-screen bg-[#f6f7f9] text-slate-950"><main className="mx-auto max-w-6xl px-4 py-8 md:py-12"><div className="mb-7 flex items-end justify-between gap-4"><div><p className="text-xs font-bold tracking-widest text-amber-600">ÇALIŞKAN B2B</p><h1 className="mt-1 text-3xl font-bold">Hesabım</h1><p className="mt-2 text-sm text-slate-500">Hesap, firma, teslimat ve güvenlik bilgilerinizi tek alandan yönetin.</p></div><Link href="/siparislerim" className="hidden sm:flex items-center gap-2 rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold"><Package className="h-4 w-4"/>Siparişlerim</Link></div><section className="mb-6 rounded-2xl border bg-white p-5 md:p-6"><div className="flex items-center gap-4"><div className="grid h-12 w-12 place-items-center rounded-full bg-slate-950 text-white"><User className="h-5 w-5"/></div><div><h2 className="font-semibold">B2B Müşteri Hesabı</h2><p className="text-sm text-slate-500">Firma hesabınız ve yetkili kullanıcı bilgileriniz</p></div></div></section><div className="grid gap-3 md:grid-cols-2">{items.map(({icon:Icon,title,desc})=><button key={title} className="group flex w-full items-center gap-4 rounded-2xl border bg-white p-4 text-left transition hover:border-slate-300 hover:shadow-sm"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-slate-100"><Icon className="h-5 w-5"/></div><div className="min-w-0 flex-1"><h3 className="font-semibold">{title}</h3><p className="mt-0.5 text-sm text-slate-500">{desc}</p></div><ChevronRight className="h-4 w-4 text-slate-400 group-hover:translate-x-0.5 transition"/></button>)}</div><section className="mt-7 rounded-2xl border border-red-200 bg-white p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold text-red-700">Hesabımı Sil</h2><p className="mt-1 text-sm text-slate-500">Hesap silme işlemi için güvenlik doğrulaması gerekir.</p></div><button className="inline-flex items-center justify-center gap-2 rounded-xl border border-red-200 px-4 py-2.5 text-sm font-semibold text-red-700 hover:bg-red-50"><Trash2 className="h-4 w-4"/>Hesabımı Sil</button></div></section></main></div>}
