import type { Express } from "express";
import { q, requireAdmin } from "./auth";
const APPS=["b2b","business"] as const,KINDS=["logo","splash"] as const;
const validApp=(v:any)=>APPS.includes(v),validKind=(v:any)=>KINDS.includes(v);
export function registerBrandingRoutes(app:Express):void{
 app.get("/api/app-branding/:app/:kind",async(req,res)=>{try{if(!validApp(req.params.app)||!validKind(req.params.kind))return res.sendStatus(404);const r=await q("SELECT mime,content,updated_at FROM app_branding WHERE app=$1 AND kind=$2",[req.params.app,req.params.kind]);if(!r.rows[0])return res.sendStatus(404);res.setHeader("Content-Type",r.rows[0].mime);res.setHeader("Cache-Control","public,max-age=3600");res.send(r.rows[0].content);}catch(e){console.error(e);res.sendStatus(500);}});
 app.get("/api/admin/app-branding",async(req,res)=>{try{if(!requireAdmin(req))return res.status(403).json({error:"Yönetici yetkisi gerekiyor"});const r=await q("SELECT app,kind,updated_at FROM app_branding");const out:any={b2b:{logo:null,splash:null},business:{logo:null,splash:null}};for(const x of r.rows)out[x.app][x.kind]=`/api/app-branding/${x.app}/${x.kind}?v=${new Date(x.updated_at).getTime()}`;res.json(out);}catch(e){console.error(e);res.status(500).json({error:"Uygulama görselleri alınamadı"});}});
 app.post("/api/admin/app-branding",async(req,res)=>{try{if(!requireAdmin(req))return res.status(403).json({error:"Yönetici yetkisi gerekiyor"});const {app:appName,kind,dataUrl}=req.body||{};if(!validApp(appName)||!validKind(kind)||typeof dataUrl!=="string")return res.status(400).json({error:"Geçersiz uygulama veya görsel türü"});const m=dataUrl.match(/^data:(image\/(?:png|jpeg|webp));base64,([A-Za-z0-9+/=]+)$/);if(!m)return res.status(400).json({error:"PNG, JPG veya WEBP görsel yükleyin"});const b=Buffer.from(m[2],"base64");if(!b.length||b.length>5*1024*1024)return res.status(400).json({error:"Görsel boyutu en fazla 5 MB olabilir"});await q("INSERT INTO app_branding(app,kind,mime,content,updated_at) VALUES($1,$2,$3,$4,NOW()) ON CONFLICT(app,kind) DO UPDATE SET mime=EXCLUDED.mime,content=EXCLUDED.content,updated_at=NOW()",[appName,kind,m[1],b]);res.json({app:appName,kind,url:`/api/app-branding/${appName}/${kind}?v=${Date.now()}`});}catch(e){console.error(e);res.status(500).json({error:"Görsel kaydedilemedi"});}});
}
