import type { Express } from "express";
import crypto from "crypto";
import { hashPassword, q, requireAdmin } from "./auth";

export function registerBusinessAdminRoutes(app: Express): void {
 app.get("/api/admin/business-users",async(req,res)=>{try{if(!requireAdmin(req))return res.status(403).json({error:"Yönetici yetkisi gerekiyor"});const r=await q("SELECT id,email,role,app_access,is_active,created_at FROM auth_users WHERE app_access='business' ORDER BY created_at DESC");res.json(r.rows.map((u:any)=>({id:u.id,email:u.email,role:u.role,appAccess:u.app_access,isActive:u.is_active,createdAt:u.created_at})));}catch(e){console.error(e);res.status(500).json({error:"Yönetici hesapları alınamadı"});}});
 app.post("/api/admin/business-users",async(req,res)=>{try{if(!requireAdmin(req))return res.status(403).json({error:"Yönetici yetkisi gerekiyor"});const email=String(req.body?.email||"").trim().toLowerCase(),password=String(req.body?.password||"");if(!email.includes("@")||password.length<8)return res.status(400).json({error:"Geçerli e-posta ve en az 8 karakter şifre gerekli"});const id=crypto.randomUUID();await q("INSERT INTO auth_users(id,email,password_hash,role,app_access) VALUES($1,$2,$3,'manager','business')",[id,email,hashPassword(password)]);res.status(201).json({id,email,role:"manager",appAccess:"business",isActive:true});}catch(e:any){if(e?.code==="23505")return res.status(409).json({error:"Bu e-posta zaten kayıtlı"});console.error(e);res.status(500).json({error:"Yönetici hesabı oluşturulamadı"});}});
 app.patch("/api/admin/business-users/:id",async(req,res)=>{try{if(!requireAdmin(req))return res.status(403).json({error:"Yönetici yetkisi gerekiyor"});const active=req.body?.isActive!==false;const r=await q("UPDATE auth_users SET is_active=$1,updated_at=NOW() WHERE id=$2 AND app_access='business' RETURNING id,email,role,app_access,is_active",[active,req.params.id]);if(!r.rows[0])return res.status(404).json({error:"Hesap bulunamadı"});if(!active)await q("DELETE FROM auth_sessions WHERE user_id=$1",[req.params.id]);const u=r.rows[0];res.json({id:u.id,email:u.email,role:u.role,appAccess:u.app_access,isActive:u.is_active});}catch(e){console.error(e);res.status(500).json({error:"Yönetici hesabı güncellenemedi"});}});
}
