-- RMA document metadata
create table if not exists public.rma_attachments (
  id bigint generated by default as identity primary key,
  ticket_id integer not null references public.tickets(id) on delete cascade,
  product_id integer references public.products(id) on delete cascade,
  file_name text not null,
  file_path text not null unique,
  mime_type text,
  size_bytes bigint,
  document_type text not null default 'attachment',
  created_at timestamptz not null default now()
);

create index if not exists rma_attachments_ticket_id_idx on public.rma_attachments(ticket_id);
create index if not exists rma_attachments_product_id_idx on public.rma_attachments(product_id);

-- Private buckets: customer/RMA documents must never be public by default.
insert into storage.buckets (id, name, public, file_size_limit)
values
  ('rma-attachments', 'rma-attachments', false, 52428800),
  ('rma-pdfs', 'rma-pdfs', false, 10485760)
on conflict (id) do nothing;

alter table public.rma_attachments enable row level security;

-- First mobile phase: only authenticated Supabase users can work with RMA files.
-- Role/branch/tenant-specific rules will replace these broad authenticated policies later.
create policy "authenticated can read rma metadata"
on public.rma_attachments for select
to authenticated
using (true);

create policy "authenticated can create rma metadata"
on public.rma_attachments for insert
to authenticated
with check (true);

create policy "authenticated can update rma metadata"
on public.rma_attachments for update
to authenticated
using (true)
with check (true);

create policy "authenticated can delete rma metadata"
on public.rma_attachments for delete
to authenticated
using (true);

create policy "authenticated can read rma files"
on storage.objects for select
to authenticated
using (bucket_id in ('rma-attachments', 'rma-pdfs'));

create policy "authenticated can upload rma files"
on storage.objects for insert
to authenticated
with check (bucket_id in ('rma-attachments', 'rma-pdfs'));

create policy "authenticated can update rma files"
on storage.objects for update
to authenticated
using (bucket_id in ('rma-attachments', 'rma-pdfs'))
with check (bucket_id in ('rma-attachments', 'rma-pdfs'));

create policy "authenticated can delete rma files"
on storage.objects for delete
to authenticated
using (bucket_id in ('rma-attachments', 'rma-pdfs'));
