-- Base tables mirror the existing Drizzle schema so this migration can run on a fresh Supabase project.
create table if not exists public.users (
  id serial primary key,
  username text not null unique,
  password text not null
);

create table if not exists public.customers (
  id serial primary key,
  name text default 'Bilinmeyen',
  phone text default '-',
  email text,
  address text,
  created_at timestamp not null default now()
);

create table if not exists public.tickets (
  id serial primary key,
  receipt_number text,
  customer_id integer not null references public.customers(id) on delete cascade,
  created_by_id integer not null default 1 references public.users(id),
  created_at timestamp not null default now(),
  updated_at timestamp not null default now()
);

create table if not exists public.products (
  id serial primary key,
  ticket_id integer not null references public.tickets(id) on delete cascade,
  name text default 'Bilinmeyen',
  serial_number text,
  brand text default 'Bilinmeyen',
  model text,
  category text default 'servis',
  status text not null default 'beklemede',
  description text,
  quantity integer default 1,
  created_at timestamp not null default now()
);

create table if not exists public.status_history (
  id serial primary key,
  product_id integer not null references public.products(id) on delete cascade,
  status text not null,
  notes text,
  created_at timestamp not null default now()
);

insert into public.users (id, username, password)
values (1, 'system', 'system')
on conflict (id) do nothing;

-- RMA document metadata.
create table if not exists public.rma_attachments (
  id bigint generated by default as identity primary key,
  ticket_id integer not null references public.tickets(id) on delete cascade,
  product_id integer references public.products(id) on delete cascade,
  file_name text not null,
  file_path text not null unique,
  mime_type text,
  size_bytes bigint,
  document_type text not null default 'attachment',
  created_at timestamptz not null default now()
);

create index if not exists rma_attachments_ticket_id_idx on public.rma_attachments(ticket_id);
create index if not exists rma_attachments_product_id_idx on public.rma_attachments(product_id);

-- Customer/RMA documents are private by default.
insert into storage.buckets (id, name, public, file_size_limit)
values
  ('rma-attachments', 'rma-attachments', false, 52428800),
  ('rma-pdfs', 'rma-pdfs', false, 10485760)
on conflict (id) do nothing;

alter table public.rma_attachments enable row level security;

-- Initial mobile phase: authenticated users can work with RMA files.
-- These policies will be narrowed to company/branch/role ownership when the auth model is added.
drop policy if exists "authenticated can read rma metadata" on public.rma_attachments;
create policy "authenticated can read rma metadata"
on public.rma_attachments for select
to authenticated
using (true);

drop policy if exists "authenticated can create rma metadata" on public.rma_attachments;
create policy "authenticated can create rma metadata"
on public.rma_attachments for insert
to authenticated
with check (true);

drop policy if exists "authenticated can update rma metadata" on public.rma_attachments;
create policy "authenticated can update rma metadata"
on public.rma_attachments for update
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated can delete rma metadata" on public.rma_attachments;
create policy "authenticated can delete rma metadata"
on public.rma_attachments for delete
to authenticated
using (true);

drop policy if exists "authenticated can read rma files" on storage.objects;
create policy "authenticated can read rma files"
on storage.objects for select
to authenticated
using (bucket_id in ('rma-attachments', 'rma-pdfs'));

drop policy if exists "authenticated can upload rma files" on storage.objects;
create policy "authenticated can upload rma files"
on storage.objects for insert
to authenticated
with check (bucket_id in ('rma-attachments', 'rma-pdfs'));

drop policy if exists "authenticated can update rma files" on storage.objects;
create policy "authenticated can update rma files"
on storage.objects for update
to authenticated
using (bucket_id in ('rma-attachments', 'rma-pdfs'))
with check (bucket_id in ('rma-attachments', 'rma-pdfs'));

drop policy if exists "authenticated can delete rma files" on storage.objects;
create policy "authenticated can delete rma files"
on storage.objects for delete
to authenticated
using (bucket_id in ('rma-attachments', 'rma-pdfs'));
